services:
  - type: web
    runtime: docker
    name: diamond-welcome-bot
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
